schema_version: 1

context:
  version: "0.4.0"

package:
  name: editdistpy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/editdistpy/editdistpy-${{ version }}.tar.gz
  sha256: bc64c0d0c4fe23a09e4b02693c5591a01d2ede7001bc55fcf92c117f68cd0896

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.13,<2
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - editdistpy
      pip_check: true

about:
  summary: Fast Levenshtein and Damerau optimal string alignment algorithms.
  description: |
    editdistpy is a fast implementation of the Levenshtein and Damerau
    optimal string alignment (OSA) edit distance algorithms, written as a
    Rust extension. It is used by symspellpy for spelling correction.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/mammothb/editdistpy
  repository: https://github.com/mammothb/editdistpy

extra:
  recipe-maintainers:
    - jm-rivera
